# Generated by Django 3.2.9 on 2021-11-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_actor_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
