# Generated by Django 3.2.9 on 2021-11-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_director_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='sinopsis',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
