# Generated by Django 3.2.9 on 2021-11-24 08:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_film_sinopsis'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('p', 'Prestada'), ('d', 'Disponible'), ('r', 'Reservada')], default='d', max_length=1)),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.film')),
            ],
        ),
    ]
