# Generated by Django 3.2.9 on 2021-12-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_filminstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filminstance',
            options={'ordering': ['fecha_devolucion']},
        ),
    ]
