# Generated by Django 3.2.9 on 2021-12-08 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_filminstance_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filminstance',
            old_name='status',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='filminstance',
            old_name='film',
            new_name='pelicula',
        ),
        migrations.RenameField(
            model_name='filminstance',
            old_name='borrower',
            new_name='solicitante',
        ),
    ]
