# Generated by Django 3.2.9 on 2021-12-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20211208_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='first_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='date_of_birth',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='last_name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='sex',
            new_name='sexo',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='first_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='date_of_birth',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='last_name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='sex',
            new_name='sexo',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='release_date',
            new_name='fecha_salida',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='genre',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='star',
            new_name='protagonista',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='title',
            new_name='titulo',
        ),
    ]
