# Generated by Django 3.2.9 on 2021-12-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20211209_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
